apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: bastion
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-06-21
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastion
  role: Bastion
  subnets:
  - utility-ap-southeast-1a
  - utility-ap-southeast-1b
  - utility-ap-southeast-1c
